version: 2
updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    groups:
      gh-actions:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    groups:
      npm:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"

  # ReVanced Manager Flutter
  - package-ecosystem: pub
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
    groups:
      pubspec:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: gradle
    labels: []
    directory: /android
    target-branch: dev
    schedule:
      interval: monthly
    groups:
      gradle:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"

  # ReVanced Manager Compose
  - package-ecosystem: gradle
    labels: [ "ReVanced Manager Compose" ]
    directory: /
    target-branch: compose-dev
    schedule:
      interval: monthly
    groups:
      gradle-compose:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
